
modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="tbmem" #mandatory

version="1.16.5-1.0.0" #mandatory

displayName="Test Mod (may change)" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java and Cy4's Tutorials and Technovision" #optional

authors="_Shadow_" #optional

description='''
A little test mod for me to.... well test.
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
